name: buil and test Device Farm tractor maven plugin

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 11
    - name: Build with Maven
      run: mvn test
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1.24
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        files: target/surefire-reports/**/*.xml
    - name: Upload test results
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: test_results
        path: target/surefire-reports